[env]
OPENCODE_DISABLE_LSP_DOWNLOAD = true
SCCACHE_CACHE_SIZE = "64G"

[settings]
lockfile = true
all_compile = false

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true

[settings.rust]
cargo_home = "/home/merrkry/.local/share/cargo"
rustup_home = "/home/merrkry/.local/share/rustup"

[tools]
# Language toolchains
ninja = "latest"
meson = "latest"
## frontend
node = "latest"
npm = "latest"
bun = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:oxfmt" = "latest"
"npm:vscode-langservers-extracted" = "latest"
# github actions
actionlint = "latest"
## go
go = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
# python
python = "latest"
uv = "latest"
"pipx:ruff" = "latest"
"pipx:zuban" = "latest"
## rust
mold = "latest"
cargo-binstall = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-sort" = "latest"
# toml
taplo = "latest"
## typst
typst = "latest"
tinymist = "latest"
# yaml
"npm:yaml-language-server" = "latest"

# Utilities
## AI
opencode = "latest"
codex = "latest"
## VCS
difftastic = "latest"
jujutsu = "latest"
gh = "latest"
## Task runners
just = "latest"
task = "latest"
websocat = "latest"
"npm:node-gyp" = "latest"
tree-sitter = "latest"
sccache = "latest"
