# https://github.com/CptPotato/helix-themes/pull/11/files
theme = "edge"

[editor]
line-number = "relative"
cursorline = false
continue-comments = false
auto-format = false
idle-timeout = 10
completion-timeout = 5
completion-replace = true
color-modes = true
end-of-line-diagnostics = "hint"

[editor.lsp]
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"
normal = "underline" # https://github.com/helix-editor/helix/issues/12642

[editor.auto-save]
focus-lost = true
after-delay = { enable = true }

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
pagedown = "half_page_down"
pageup = "half_page_up"
"C-l" = ":format"
"C-s" = ":write"
"C-S-s" = ":write-all"
"C-r" = ":reload"
"C-S-r" = ":reload-all"
J = [
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
]
K = [
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
]
ret = "goto_word"

[keys.insert]
pagedown = "half_page_down"
pageup = "half_page_up"

[keys.select]
pagedown = "half_page_down"
pageup = "half_page_up"
