[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser markdown"] }

[[language]]
language-servers = ["nixd"]
name = "nix"
formatter = { command = "nixfmt", args = ["--strict", "-"] }

[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
config = { basedpyright = { analysis = { typeCheckingMode = "standard" } } }

[language-server.rust-analyzer.config]
check = { command = "clippy" }
