[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser markdown"] }

[[language]]
language-servers = ["nixd"]
name = "nix"
formatter = { command = "nixfmt", args = ["--strict", "-"] }

[[language]]
name = "python"
language-servers = ["pyright"]
formatter = { command = "ruff", args = ["format", "-"] }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
